# Generated by Django 3.2.4 on 2021-09-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('Private and Luxury', 'Private and Luxury'), ('Full-day Tours', 'Full-day Tours'), ('Day trips', 'Day trips')], max_length=50, verbose_name='Place Type'),
        ),
    ]
